runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7.12.2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
    - name: Installing packages...🏃‍♂️ 🏃‍♂️ 🏃‍♂️
      run: pnpm install --frozen-lockfile
